## Rubric

Instructions: DELETE this cell before you submit via a `git push` to your repo before deadline. This cell is for your reference only and is not needed in your report. 

 Scoring: Out of 10 points

- Each Developing  => -2 pts
- Each Unsatisfactory/Missing => -4 pts
  - until the score is 0

If students address the detailed feedback in a future checkpoint they will earn these points back






|                                  | **Unsatisfactory**                                                                                                                                                                                                                                                                                                                        | **Developing**                                                                                                                                                                                                       | **Proficient**                                                                                                                                                                                            | **Excellent**                                                                                                                                                                            |
|----------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **EDA relevance**                | EDA is mostly neither relevant to the question nor helpful in figuring out how to address the question. Or the EDA does address the question, but many obviously relevant variables / analyses / figures were not included. | EDA is partly irrelevant/unhelpful. EDA missed one or two obvioulsy relevant analysis (distributions of single variables or relationships between variables) | EDA includes the obviously relevant / helpful variables in addressing the question.                                                              | Thorough EDA fully explored the dataset                                                                                                                 |
| **EDA analysis and description** | Many of the analyses are poor choices (e.g., using means instead of medians for obviously skewed data), or are poorly described in the text, or do not aid understanding the data                                                                                                                                                     | Some of the analyses are poor choices, or are poorly described in the text, or do not aid understanding the data                                                                                                 | All analyses are correct choices. Only one or two have minor issues in the text descriptions supporting them. Mostly they fit well with other elements of the EDA and support understanding the data  | All analyses are correct choices with clear text descriptions supporting them. The figures fit well with the other elements of the EDA, producing a clear understanding of the data. |
| **EDA figures**                  | Many of the figures are poor plot choices (e.g., using a bar plot to represent a time series where it would be better to use a line plot) or have poor aesthetics (including colormap, data point shape/color, axis labels, titles, annotations, text legibility) or do not aid understanding the data                                | Some of the figures are poor plot choices or have poor aesthetics. Some figures do not aid understanding the data                                                                                                | All figures are correct plot choices. Only one or two have minor questionable aesthetic choices. The figures mostly fit well with the other elements of the EDA and support understanding the data    | All figures are correct plot choices with beautiful aesthetics. The figures fit well with the other elements of the EDA, producing a clear understanding of the data.                |

# COGS 108 - EDA Checkpoint

## Authors

Instructions: REPLACE the contents of this cell with your team list and their contributions. Note that this will change over the course of the checkpoints

This is a modified [CRediT taxonomy of contributions](https://credit.niso.org). For each group member please list how they contributed to this project using these terms:
> Analysis, Background research, Conceptualization, Data curation, Experimental investigation, Methodology, Project administration, Software, Visualization, Writing – original draft, Writing – review & editing

Example team list and credits:
- Alice Anderson: Conceptualization, Data curation, Methodology, Writing - original draft
- Bob Barker:  Analysis, Software, Visualization
- Charlie Chang: Project administration, Software, Writing - review & editing
- Dani Delgado: Analysis, Background research, Visualization, Writing - original draft

# Research Question

Is there a relationship between the COGS course drop rate at UCSD and students' evaluations of these courses - specifically course workload (study hours per week), instructor ratings, and average course grades - using CAPE evaluation data from 2022-23 school year (FA22 - SP23), on COGS1, 14A, 17, 101B, and 107A?

## Background and Prior Work

It's so common for college students to choose to drop their courses within the beginning few weeks of a new quarter, that we often overlook the significance behind this behavior: what factors could actually be correlated with this complex decision - giving up a course that is planned or even anticipated for months since registration? Specifically, aside from non-academic reasons, what aspects of a course itself may be associated with a high withdrawal rate?

One previous research has been conducted on the affective reasoning of why students might choose to withdraw courses.<a name="cite_ref-1"></a>[<sup>1</sup>](#cite_note-1) Among the multiple reasons for dropping from a course, "at risk of failing the course" is ranked at the top with a 39.9% probability of withdrawing. In other words, students may tend to drop courses if they feel they may get bad grades, mainly due to the difficulty, as the courses continue. 

Another research has pointed out that "assignment too heavy" could be a reason of dropping courses as well.<a name="cite_ref-2"></a>[<sup>2</sup>](#cite_note-2) This term, first of all, may be regarded as an implication of the difficulty of the course. However, this research was conducted through community colleges, and academic workload is related to job conflict (time conflict) specifically in this case. Therefore, heavy assignments also represent time consuming tasks. 

We also discovered a prior study that takes the teaching quality into account.<a name="cite_ref-3"></a>[<sup>3</sup>](#cite_note-3) By examining SRT (students rating of teaching) data, the researchers show that students can have their own evaluations of the instructors only after taking a few classes, which is then a critical factor of if the students will drop the course. Noteworthy, this factor is isolated from the probability of receiving bad grades or being assigned heavy tasks, because teaching methods or attitudes of professors do not necessarily relate to their assignments or rating scales.

Drawing on the findings of the researches above, we include three major instructional factors - average course grades, course workload (work time), and instructor ratings - in our research of their correlations to the students' dropping rate of COGS courses at UCSD, examining if they show the same correlations in our case as well.


1. <a name="cite_note-1"></a> [^](#cite_ref-1) Wheland, E., Butler, J., Qammar, H., & Katz-Harris, S. (n.d.). *What Are They Thinking? Students’ Affective Reasoning and Attitudes about Course Withdrawal* (pp. 17–25). https://www.montana.edu/rmaher/barrier_courses/32-2-Wheland-Butler-Qammar-Katz%20Harris-pp17-25.pdf
2. <a name="cite_note-2"></a> [^](#cite_ref-2) Friedlander, J. (1981). *Why Students Drop Courses*. Junior College Resource Review (ERIC Document ED196505). https://files.eric.ed.gov/fulltext/ED196505.pdf
3. <a name="cite_note-3"></a> [^](#cite_ref-3) Babad, E., Icekson, T., & Yelinek, Y. (2008). *Antecedents and correlates of course cancellation in a university “drop and add” period*. Research in Higher Education, 49(4), 293–316. https://doi.org/10.1007/s11162-007-9082-3

# Hypothesis

We predict that there is likely a strong correlation between COGS course drop rate at UCSD and students' evaluations. We predict that courses with a higher workload, lower professor rating and lower grades are likely to have a higher drop rate. All these factors represent a class with a higher difficulty, which we believe will lead to a greater number of students dropping said class.

## Data

### Data overview

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your data checkpoint feedback

In [31]:
import pandas as pd
import os 
def drop_rate(course):
    diff = course['enrolled'].diff().fillna(0)
    total_enroll = int(diff[diff > 0].sum())
    total_drop = int((-diff[diff < 0]).sum())
    if total_enroll == 0:
        drop_rate = 0
    else:
        drop_rate = round((total_drop / total_enroll) * 100, 2)
    return total_enroll, total_drop, drop_rate

def quarter_to_df(file):
    results = []
    for filename in os.listdir(file):
        if filename.endswith(".csv"):
            file_path = os.path.join(file, filename)
            df = pd.read_csv(file_path)
            enroll, drop, rate = drop_rate(df)
            course_name = filename.replace(".csv", "")
            results.append({"course": course_name, "total_enrolled": enroll, \
                "total_dropped": drop, "drop_rate_percent": rate})
    results_df = pd.DataFrame(results)
    results_df = results_df.set_index("course")
    return results_df

In [33]:
WI23

In [34]:
FA22 = quarter_to_df("data/00-raw/COGS_22FA/")
SP23 = quarter_to_df("data/00-raw/COGS_23SP/")
WI23 = quarter_to_df("data/00-raw/COGS_23WI/")

In [35]:
FA22

           total_enrolled  total_dropped  drop_rate_percent
course
COGS 11               230             79              34.35
COGS 18               418             75              17.94
COGS 87                77             46              59.74
COGS 8                 25             14              56.00
COGS 143               55             13              23.64
COGS 1                516            106              20.54
COGS 187A             178             23              12.92
COGS 120              265             61              23.02
COGS 14B              239             64              26.78
COGS 160               16              5              31.25
COGS 9                427            118              27.63
COGS 101A             425             84              19.76
COGS 194                0              0               0.00
COGS 17               410             91              22.20
COGS 10               402            115              28.61
COGS 128               59             20              33.90
COGS 153               77              2               2.60
COGS 110              110             42              38.18
COGS 190A              10              0               0.00
COGS 107A             490             69              14.08
COGS 3                258             86              33.33
COGS 101B             207             23              11.11
COGS 197                7              0               0.00
COGS 108              502             70              13.94
COGS 13               268            209              77.99
COGS 118B             269            115              42.75
COGS 14A              392             74              18.88
COGS 116              129             38              29.46
COGS 15               208             93              44.71
COGS 100              386             87              22.54
COGS 175               51             28              54.90
COGS 102A             140             73              52.14
COGS 101C             201             50              24.88
COGS 198                1              0               0.00
COGS 20                29             10              34.48
COGS 2                285             77              27.02

In [36]:
SP23

           total_enrolled  total_dropped  drop_rate_percent
course
COGS 14A              322             26               8.07
COGS 164              170             32              18.82
COGS 101A             158             30              18.99
COGS 109              190             53              27.89
COGS 100              386             45              11.66
COGS 198                5              1              20.00
COGS 12               151            110              72.85
COGS 118A             218             65              29.82
COGS 107C             238             26              10.92
COGS 122               68              9              13.24
COGS 125               41             11              26.83
COGS 190D               9              0               0.00
COGS 157               96             30              31.25
COGS 190C              10              1              10.00
COGS 13               316             26               8.23
COGS 197                4              0               0.00
COGS 108              486             55              11.32
COGS 17               401             46              11.47
COGS 194                0              0               0.00
COGS 142               72             24              33.33
COGS 9                392             98              25.00
COGS 170              110             17              15.45
COGS 99                 4              0               0.00
COGS 121              136             15              11.03
COGS 185              115             27              23.48
COGS 8                 49             15              30.61
COGS 101B             313             24               7.67
COGS 87                37             24              64.86
COGS 1                521             61              11.71
COGS 18               387             44              11.37
COGS 138               56             17              30.36
COGS 144               74             26              35.14
COGS 184               65             22              33.85
COGS 155               71             18              25.35
COGS 14B              232             37              15.95
COGS 112              227             39              17.18
COGS 107A             383             45              11.75
COGS 160               15              0               0.00

In [ ]:
# Run this code every time when you're actively developing modules in .py files.  It's not needed if you aren't making modules
#
## this code is necessary for making sure that any modules we load are updated here 
## when their source code .py files are modified

%load_ext autoreload
%autoreload 2

In [ ]:
# Setup code -- Run only once after cloning!!! 
#
# this code downloads the data from its source to the `data/00-raw/` directory
# if the data hasn't updated you don't need to do this again!

# if you don't already have these packages (you should!) uncomment this line
# %pip install requests tqdm

import sys
sys.path.append('./modules') # this tells python where to look for modules to import

import get_data # this is where we get the function we need to download data

# replace the urls and filenames in this list with your actual datafiles
# yes you can use Google drive share links or whatever
# format is a list of dictionaries; 
# each dict has keys of 
#   'url' where the resource is located
#   'filename' for the local filename where it will be stored 
datafiles = [
    { 'url': 'https://raw.githubusercontent.com/fivethirtyeight/data/refs/heads/master/airline-safety/airline-safety.csv', 'filename':'airline-safety.csv'},
    { 'url': 'https://raw.githubusercontent.com/fivethirtyeight/data/refs/heads/master/bad-drivers/bad-drivers.csv', 'filename':'bad-drivers.csv'}
]

get_data.get_raw(datafiles,destination_directory='data/00-raw/')

### Dataset #1 

Instructions: REPLACE the contents of this cell and the one below with your work, including any updates to recover points lost in your data checkpoint feedback

In [ ]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

### Dataset #2
 as above, add any more copies of this that you need to given how many datasets you have

In [ ]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

## Results

### Exploratory Data Analysis

Instructions: replace the words in this subsection with whatever words you need to setup and preview the EDA you're going to do.   

Please explicitly load the fully wrangled data you will use from `data/02-processed`.  This is a good idea rather than forcing people to re-run the data getting / wrangling cells above.  Sometimes it takes a long time to get / wrangle data compared to reloading the fixed up dataset.

Carry out whatever EDA you need to for your project in the code cells below.  Because every project will be different we can't really give you much of a template at this point. But please make sure you describe the what and why in text here as well as providing interpretation of results and context.

Please note that you should consider the use of python modules in your work.  Any code which gets called repeatedly should be modularized. So if you run the same pre-processing, analysis or visualiazation on different subsets of the data, then you should turn that into a function or class.  Put that function or class in a .py file that lives in `modules/`.  Import the module you made and use it to get your work done.  For reference see `get_raw()` which is inside `modules/get_data.py`.

#### Section 1 of EDA - please give it a better title than this

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.

In [ ]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

#### Section 2 of EDA if you need it  - please give it a better title than this

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.

In [ ]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

## Ethics

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Team Expectations

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Project Timeline Proposal

Instructions: Replace this with your timeline.  **PLEASE UPDATE your Timeline!** No battle plan survives contact with the enemy, so make sure we understand how your plans have changed.  Also if you have lost points on the previous checkpoint fix them